workflows:
  android-app-build:
    name: Android App Build
    instance_type: mac_mini_m1
    environment:
      groups:
        - android-sdk
      java: 17
    scripts:
      - name: Grant execute permission to gradlew
        script: chmod +x ./gradlew
      - name: Build debug APK
        script: ./gradlew assembleDebug -Dorg.gradle.jvmargs="-Xmx2048m -Dfile.encoding=UTF-8 --add-opens java.base/java.io=ALL-UNNAMED"
    artifacts:
      - app/build/outputs/apk/debug/*.apk
